version: '3.2'

services:
  redis:
    restart: always
    container_name: gcs-viewer-redis
    image: redis:alpine3.12
    networks:
      - default

  api:
    restart: always
    build: api
    container_name: gcs-viewer-api
    depends_on:
      - redis
    networks:
      - default
    ports:
      - ${API_PORT}:3001
    environment:
      - USER_EMAIL=${USER_EMAIL}
      - USER_PASSWORD=${USER_PASSWORD}
      - TRAINING_SERVICE_ACCOUNT_FILE=${TRAINING_SERVICE_ACCOUNT_FILE}
      - TRAINING_SERVICE_ACCOUNT_PROJECT=${TRAINING_SERVICE_ACCOUNT_PROJECT}
      - TRAINING_SERVICE_ACCOUNT_BUCKET_NAME=${TRAINING_SERVICE_ACCOUNT_BUCKET_NAME}
      - PORT=3001
    volumes:
      - ./downloads:/app/downloads
      - ./${TRAINING_SERVICE_ACCOUNT_FILE}:/app/${TRAINING_SERVICE_ACCOUNT_FILE}

  frontend:
    restart: always
    build:
      context: frontend
      args:
        - VITE_BASE_GCS_PATH=${VITE_BASE_GCS_PATH}
        - VITE_API_URL=${VITE_API_URL}
    depends_on:
      - api
    networks:
      - default
    ports:
      - ${FRONTEND_PORT}:80

networks:
    default:
        driver: bridge